#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.36241
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DatabaseApps
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="MusicGame_db")]
	public partial class MusicGameDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMG_Question(MG_Question instance);
    partial void UpdateMG_Question(MG_Question instance);
    partial void DeleteMG_Question(MG_Question instance);
    partial void InsertMG_Artist(MG_Artist instance);
    partial void UpdateMG_Artist(MG_Artist instance);
    partial void DeleteMG_Artist(MG_Artist instance);
    partial void InsertMG_Song(MG_Song instance);
    partial void UpdateMG_Song(MG_Song instance);
    partial void DeleteMG_Song(MG_Song instance);
    #endregion
		
		public MusicGameDataContext() : 
				base(global::DatabaseApps.Properties.Settings.Default.MusicGame_dbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public MusicGameDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MusicGameDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MusicGameDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MusicGameDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MG_Question> MG_Questions
		{
			get
			{
				return this.GetTable<MG_Question>();
			}
		}
		
		public System.Data.Linq.Table<MG_Artist> MG_Artists
		{
			get
			{
				return this.GetTable<MG_Artist>();
			}
		}
		
		public System.Data.Linq.Table<MG_Song> MG_Songs
		{
			get
			{
				return this.GetTable<MG_Song>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MG_Question")]
	public partial class MG_Question : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdQuestion;
		
		private System.Nullable<int> _Type;
		
		private string _Source;
		
		private string _TextQuestion;
		
		private string _Description;
		
		private string _A;
		
		private string _B;
		
		private string _C;
		
		private string _D;
		
		private string _Answer;
		
		private string _Genre;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdQuestionChanging(int value);
    partial void OnIdQuestionChanged();
    partial void OnTypeChanging(System.Nullable<int> value);
    partial void OnTypeChanged();
    partial void OnSourceChanging(string value);
    partial void OnSourceChanged();
    partial void OnTextQuestionChanging(string value);
    partial void OnTextQuestionChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnAChanging(string value);
    partial void OnAChanged();
    partial void OnBChanging(string value);
    partial void OnBChanged();
    partial void OnCChanging(string value);
    partial void OnCChanged();
    partial void OnDChanging(string value);
    partial void OnDChanged();
    partial void OnAnswerChanging(string value);
    partial void OnAnswerChanged();
    partial void OnGenreChanging(string value);
    partial void OnGenreChanged();
    #endregion
		
		public MG_Question()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdQuestion", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdQuestion
		{
			get
			{
				return this._IdQuestion;
			}
			set
			{
				if ((this._IdQuestion != value))
				{
					this.OnIdQuestionChanging(value);
					this.SendPropertyChanging();
					this._IdQuestion = value;
					this.SendPropertyChanged("IdQuestion");
					this.OnIdQuestionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int")]
		public System.Nullable<int> Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this.OnTypeChanging(value);
					this.SendPropertyChanging();
					this._Type = value;
					this.SendPropertyChanged("Type");
					this.OnTypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Source", DbType="NVarChar(100)")]
		public string Source
		{
			get
			{
				return this._Source;
			}
			set
			{
				if ((this._Source != value))
				{
					this.OnSourceChanging(value);
					this.SendPropertyChanging();
					this._Source = value;
					this.SendPropertyChanged("Source");
					this.OnSourceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TextQuestion", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string TextQuestion
		{
			get
			{
				return this._TextQuestion;
			}
			set
			{
				if ((this._TextQuestion != value))
				{
					this.OnTextQuestionChanging(value);
					this.SendPropertyChanging();
					this._TextQuestion = value;
					this.SendPropertyChanged("TextQuestion");
					this.OnTextQuestionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Description", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_A", DbType="NVarChar(50)")]
		public string A
		{
			get
			{
				return this._A;
			}
			set
			{
				if ((this._A != value))
				{
					this.OnAChanging(value);
					this.SendPropertyChanging();
					this._A = value;
					this.SendPropertyChanged("A");
					this.OnAChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_B", DbType="NVarChar(50)")]
		public string B
		{
			get
			{
				return this._B;
			}
			set
			{
				if ((this._B != value))
				{
					this.OnBChanging(value);
					this.SendPropertyChanging();
					this._B = value;
					this.SendPropertyChanged("B");
					this.OnBChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C", DbType="NVarChar(50)")]
		public string C
		{
			get
			{
				return this._C;
			}
			set
			{
				if ((this._C != value))
				{
					this.OnCChanging(value);
					this.SendPropertyChanging();
					this._C = value;
					this.SendPropertyChanged("C");
					this.OnCChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_D", DbType="NVarChar(50)")]
		public string D
		{
			get
			{
				return this._D;
			}
			set
			{
				if ((this._D != value))
				{
					this.OnDChanging(value);
					this.SendPropertyChanging();
					this._D = value;
					this.SendPropertyChanged("D");
					this.OnDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Answer", DbType="NVarChar(50)")]
		public string Answer
		{
			get
			{
				return this._Answer;
			}
			set
			{
				if ((this._Answer != value))
				{
					this.OnAnswerChanging(value);
					this.SendPropertyChanging();
					this._Answer = value;
					this.SendPropertyChanged("Answer");
					this.OnAnswerChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Genre", DbType="NVarChar(30)")]
		public string Genre
		{
			get
			{
				return this._Genre;
			}
			set
			{
				if ((this._Genre != value))
				{
					this.OnGenreChanging(value);
					this.SendPropertyChanging();
					this._Genre = value;
					this.SendPropertyChanged("Genre");
					this.OnGenreChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MG_Artist")]
	public partial class MG_Artist : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdArtist;
		
		private string _NameArtist;
		
		private string _Nation;
		
		private EntitySet<MG_Song> _MG_Songs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdArtistChanging(int value);
    partial void OnIdArtistChanged();
    partial void OnNameArtistChanging(string value);
    partial void OnNameArtistChanged();
    partial void OnNationChanging(string value);
    partial void OnNationChanged();
    #endregion
		
		public MG_Artist()
		{
			this._MG_Songs = new EntitySet<MG_Song>(new Action<MG_Song>(this.attach_MG_Songs), new Action<MG_Song>(this.detach_MG_Songs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArtist", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdArtist
		{
			get
			{
				return this._IdArtist;
			}
			set
			{
				if ((this._IdArtist != value))
				{
					this.OnIdArtistChanging(value);
					this.SendPropertyChanging();
					this._IdArtist = value;
					this.SendPropertyChanged("IdArtist");
					this.OnIdArtistChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameArtist", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NameArtist
		{
			get
			{
				return this._NameArtist;
			}
			set
			{
				if ((this._NameArtist != value))
				{
					this.OnNameArtistChanging(value);
					this.SendPropertyChanging();
					this._NameArtist = value;
					this.SendPropertyChanged("NameArtist");
					this.OnNameArtistChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nation", DbType="NVarChar(50)")]
		public string Nation
		{
			get
			{
				return this._Nation;
			}
			set
			{
				if ((this._Nation != value))
				{
					this.OnNationChanging(value);
					this.SendPropertyChanging();
					this._Nation = value;
					this.SendPropertyChanged("Nation");
					this.OnNationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MG_Artist_MG_Song", Storage="_MG_Songs", ThisKey="IdArtist", OtherKey="IdArtist")]
		public EntitySet<MG_Song> MG_Songs
		{
			get
			{
				return this._MG_Songs;
			}
			set
			{
				this._MG_Songs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_MG_Songs(MG_Song entity)
		{
			this.SendPropertyChanging();
			entity.MG_Artist = this;
		}
		
		private void detach_MG_Songs(MG_Song entity)
		{
			this.SendPropertyChanging();
			entity.MG_Artist = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.MG_Song")]
	public partial class MG_Song : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _IdSong;
		
		private int _IdArtist;
		
		private string _NameSong;
		
		private string _Genre;
		
		private EntityRef<MG_Artist> _MG_Artist;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdSongChanging(int value);
    partial void OnIdSongChanged();
    partial void OnIdArtistChanging(int value);
    partial void OnIdArtistChanged();
    partial void OnNameSongChanging(string value);
    partial void OnNameSongChanged();
    partial void OnGenreChanging(string value);
    partial void OnGenreChanged();
    #endregion
		
		public MG_Song()
		{
			this._MG_Artist = default(EntityRef<MG_Artist>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdSong", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int IdSong
		{
			get
			{
				return this._IdSong;
			}
			set
			{
				if ((this._IdSong != value))
				{
					this.OnIdSongChanging(value);
					this.SendPropertyChanging();
					this._IdSong = value;
					this.SendPropertyChanged("IdSong");
					this.OnIdSongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IdArtist", DbType="Int NOT NULL")]
		public int IdArtist
		{
			get
			{
				return this._IdArtist;
			}
			set
			{
				if ((this._IdArtist != value))
				{
					if (this._MG_Artist.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIdArtistChanging(value);
					this.SendPropertyChanging();
					this._IdArtist = value;
					this.SendPropertyChanged("IdArtist");
					this.OnIdArtistChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NameSong", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string NameSong
		{
			get
			{
				return this._NameSong;
			}
			set
			{
				if ((this._NameSong != value))
				{
					this.OnNameSongChanging(value);
					this.SendPropertyChanging();
					this._NameSong = value;
					this.SendPropertyChanged("NameSong");
					this.OnNameSongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Genre", DbType="NVarChar(50)")]
		public string Genre
		{
			get
			{
				return this._Genre;
			}
			set
			{
				if ((this._Genre != value))
				{
					this.OnGenreChanging(value);
					this.SendPropertyChanging();
					this._Genre = value;
					this.SendPropertyChanged("Genre");
					this.OnGenreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="MG_Artist_MG_Song", Storage="_MG_Artist", ThisKey="IdArtist", OtherKey="IdArtist", IsForeignKey=true)]
		public MG_Artist MG_Artist
		{
			get
			{
				return this._MG_Artist.Entity;
			}
			set
			{
				MG_Artist previousValue = this._MG_Artist.Entity;
				if (((previousValue != value) 
							|| (this._MG_Artist.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._MG_Artist.Entity = null;
						previousValue.MG_Songs.Remove(this);
					}
					this._MG_Artist.Entity = value;
					if ((value != null))
					{
						value.MG_Songs.Add(this);
						this._IdArtist = value.IdArtist;
					}
					else
					{
						this._IdArtist = default(int);
					}
					this.SendPropertyChanged("MG_Artist");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
